version: '3'
services:

  demo_db:
    image: mysql:5.7-debian
    platform: linux/amd64
    ports:
      - "19999:3306"
    expose:
      - "19999"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: demo
